- name: Cinema Tickets App Configuration
  hosts: all
  user: vagrant
  become: yes
  vars:
    db:
      path: "./db"
      image_name: "cta_db_image"
      image_tag: 1.0
      container_name: "cta_db"
    backend:
      path: "./backend"
      image_name: "cta_app_image"
      image_tag: 1.0
      container_name: "cta_app"
    docker_bridge_network_name: 'cta-bridge'
  tasks:
    - name: Install Java (with update cache)
      apt:
        name: openjdk-11-jdk-headless
        update_cache: yes
    - name: Install Docker (with update cache)
      apt:
        name: docker.io
        update_cache: yes
    - name: Reload daemon
      command: systemctl daemon-reload
      become: true
    - name: Enable and Start docker
      service:
        name: docker
        enabled: yes
        state: started
      become: true
    - name: "[Python] Install pip"
      apt:
        name: python3-pip
        update_cache: yes
    - name: "[Python] Install docker-py"
      pip:
        name: docker
    - name: "[Maven Build] Build maven"
      shell: "./mvnw clean package -DskipTests -DdbHost={{db.container_name}}"
      ignore_errors: yes
      args:
        chdir: /vagrant/
      register: maven_build_result
    - name: "[Docker] Create network"
      docker_network:
        name: "{{docker_bridge_network_name}}"
    - name: "[Docker] Build database docker image"
      docker_image:
        build:
          path: "{{db.path}}"
        name: "{{db.image_name}}"
        tag: "{{db.image_tag}}"
    - name: "[Docker] Start database docker container"
      docker_container:
        name: "{{db.container_name}}"
        image: "{{db.image_name}}:{{db.image_tag}}"
        detach: yes
        restart_policy: always
        networks:
          - name: "{{docker_bridge_network_name}}"
        ports:
          - "3306:3306"
    - name: "[Docker] Build backend docker image"
      docker_image:
        build:
          path: "{{backend.path}}"
        name: "{{backend.image_name}}"
        tag: "{{backend.image_tag}}"
    - name: "[Docker] Start backend docker container"
      docker_container:
        name: "{{backend.container_name}}"
        image: "{{backend.image_name}}:{{backend.image_tag}}"
        detach: yes
        restart_policy: always
        networks:
          - name: "{{docker_bridge_network_name}}"
        ports:
          - "8081:8081"