- name: Cinema Tickets App Configuration
  hosts: all
  user: vagrant
  tasks:
    - name: Install Java (with update cache)
      apt:
        name: openjdk-11-jdk-headless
        update_cache: yes
      become: yes
    - name: Install Docker (with update cache)
      apt:
        name: docker.io
        update_cache: yes
      become: yes
    - name: Reload daemon
      command: systemctl daemon-reload
      become: true
    - name: Enable and Start docker
      service:
        name: docker
        enabled: yes
        state: started
      become: true
    - name: "[Python] Install pip"
      apt:
        name: python3-pip
        update_cache: yes
      become: yes
    - name: "[Python] Install docker"
      pip:
        name: docker
      become: yes
    - name: "[Python] Install missing libffi-dev (Required to install docker-compose, but for some reason not bundled in python 3.5)"
      apt:
        name: libffi-dev
      become: yes
    - name: "[Python] Install docker-compose"
      pip:
        name: docker-compose
      become: yes
    - name: "[Maven Build] Build maven"
      shell: "./mvnw clean package -DskipTests -DdbHost=cta_db"
      ignore_errors: yes
      args:
        chdir: /vagrant/
      register: maven_build_result
    - name: "[Docker] Compose services"
      docker_compose:
        project_src: "/vagrant/"
      become: yes