export const movieListConstants = {
  MOVIE_LIST_REQUEST: 'MOVIE_LIST_REQUEST',
  MOVIE_LIST_SUCCESS: 'MOVIE_LIST_SUCCESS',
  MOVIE_LIST_FAILURE: 'MOVIE_LIST_FAILURE',


  // Filters
  MOVIE_LIST_FILTERS_UPDATE: 'MOVIE_LIST_FILTERS_UPDATE',
  MOVIE_LIST_FILTERS_CLEAR: 'MOVIE_LIST_FILTERS_CLEAR'
}
