export const screeningConstants = {
    // Multiple
    MOVIE_SCREENINGS_REQUEST: 'MOVIE_SCREENINGS_REQUEST',
    MOVIE_SCREENINGS_SUCCESS: 'MOVIE_SCREENINGS_SUCCESS',
    MOVIE_SCREENINGS_FAILURE: 'MOVIE_SCREENINGS_FAILURE',

    // Set
    SET_CURRENT_SCREENING: 'SET_CURRENT_SCREENING'
}