export const seatConstants = {
    SEAT_LAYOUT_REQUEST: 'SEAT_LAYOUT_REQUEST',
    SEAT_LAYOUT_SUCCESS: 'SEAT_LAYOUT_SUCCESS',
    SEAT_LAYOUT_FAILURE: 'SEAT_LAYOUT_FAILURE',
    SEAT_RESERVATION_REQUEST: 'SEAT_RESERVATION_REQUEST',
    SEAT_RESERVATION_SUCCESS: 'SEAT_RESERVATION_SUCCESS',
    SEAT_RESERVATION_FAILURE: 'SEAT_RESERVATION_FAILURE',

    // Set seat state
    UPDATE_SEAT_STATE: 'UPDATE_SEAT_STATE',
}
