export const seatConstants = {
    SEAT_LAYOUT_REQUEST: 'SEAT_LAYOUT_REQUEST',
    SEAT_LAYOUT_SUCCESS: 'SEAT_LAYOUT_SUCCESS',
    SEAT_LAYOUT_FAILURE: 'SEAT_LAYOUT_FAILURE',


    // Set seat state
    UPDATE_SEAT_STATE: 'UPDATE_SEAT_STATE',
}
